can_linux: initialize msghdr in a portable way
musl has padding bytes inside the msghdr struct which means initializing
full structure will cause wrong assignments, doing partial assignment is
more portable and assign the elements after that

Fixes
src/core/can_linux.c:362:71: error: incompatible pointer to integer conversion initializing 'int' with an expression of type 'void *' [-Wint-conversion]
  |     struct msghdr      msg              = { &sa, sizeof(sa), &iov, 1, NULL, 0, 0 };
  |                                                                       ^~~~